package ctxkey

const (
	Config              = "config"
	Id                  = "id"
	Username            = "username"
	Role                = "role"
	CanManageUsers      = "can_manage_users"
	Status              = "status"
	Channel             = "channel"
	ChannelId           = "channel_id"
	SpecificChannelId   = "specific_channel_id"
	RequestModel        = "request_model"
	ConvertedRequest    = "converted_request"
	OriginalModel       = "original_model"
	Group               = "group"
	ModelMapping        = "model_mapping"
	ChannelModelConfigs = "channel_model_configs"
	ChannelName         = "channel_name"
	TokenId             = "token_id"
	TokenName           = "token_name"
	BaseURL             = "base_url"
	AvailableModels     = "available_models"
	KeyRequestBody      = "key_request_body"
	SystemPrompt        = "system_prompt"
	UpstreamURL         = "upstream_url"
	UpstreamStatus      = "upstream_status"
	RelayRetryCount     = "relay_retry_count"
	RelayError          = "relay_error"
)
