package ctxkey

const (
	Config                      = "config"
	Id                          = "id"
	Username                    = "username"
	Role                        = "role"
	CanManageUsers              = "can_manage_users"
	Status                      = "status"
	Channel                     = "channel"
	ChannelId                   = "channel_id"
	SpecificChannelId           = "specific_channel_id"
	RequestModel                = "request_model"
	ConvertedRequest            = "converted_request"
	OriginalModel               = "original_model"
	Group                       = "group"
	ModelMapping                = "model_mapping"
	ChannelModelConfigs         = "channel_model_configs"
	ChannelName                 = "channel_name"
	TokenId                     = "token_id"
	TokenName                   = "token_name"
	EntitlementSourceType       = "entitlement_source_type"
	EntitlementSourceId         = "entitlement_source_id"
	EntitlementSourceName       = "entitlement_source_name"
	BaseURL                     = "base_url"
	AvailableModels             = "available_models"
	ResponsesPreviousResponseID = "responses_previous_response_id"
	ResponsesStatefulRequest    = "responses_stateful_request"
	KeyRequestBody              = "key_request_body"
	UpstreamURL                 = "upstream_url"
	UpstreamStatus              = "upstream_status"
	RelayRetryCount             = "relay_retry_count"
	RelayFallbackAttempts       = "relay_fallback_attempts"
	RelayError                  = "relay_error"
	RelayErrorType              = "relay_error_type"
	RelayErrorCode              = "relay_error_code"
	RelayTermination            = "relay_termination"
)
