export const CHANNEL_PROTOCOL_OPTIONS = [
  {key: 'openai', text: 'OpenAI', value: 'openai', color: 'green'},
  {key: 'anthropic', text: 'Anthropic', value: 'anthropic', color: 'black'},
  {key: 'awsclaude', text: 'AWS', value: 'awsclaude', color: 'black'},
  {key: 'azure', text: 'Azure', value: 'azure', color: 'olive'},
  {key: 'palm', text: 'PaLM2', value: 'palm', color: 'orange'},
  {key: 'gemini', text: 'Gemini', value: 'gemini', color: 'orange'},
  {
    key: 'gemini-openai-compatible',
    text: 'Gemini (OpenAI)',
    value: 'gemini-openai-compatible',
    color: 'orange',
    description: 'Gemini OpenAI 兼容格式',
  },
  {key: 'mistral', text: 'Mistral AI', value: 'mistral', color: 'orange'},
  {key: 'novita', text: 'Novita', value: 'novita', color: 'purple'},
  {
    key: 'doubao',
    text: '字节火山引擎',
    value: 'doubao',
    color: 'blue',
    description: '原字节跳动豆包',
  },
  {
    key: 'baidu',
    text: '百度文心千帆',
    value: 'baidu',
    color: 'blue',
    tip: '请前往<a href="https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application/v1" target="_blank">此处</a>获取 AK（API Key）以及 SK（Secret Key），注意，V2 版本接口请使用 <strong>百度文心千帆 V2 </strong>渠道类型',
  },
  {
    key: 'baidu-v2',
    text: '百度文心千帆 V2',
    value: 'baidu-v2',
    color: 'blue',
    tip: '请前往<a href="https://console.bce.baidu.com/iam/#/iam/apikey/list" target="_blank">此处</a>获取 API Key，注意本渠道仅支持<a target="_blank" href="https://cloud.baidu.com/doc/WENXINWORKSHOP/s/em4tsqo3v">推理服务 V2</a>相关模型',
  },
  {
    key: 'ali',
    text: '阿里通义千问',
    value: 'ali',
    color: 'orange',
    tip: '阿里兼容模式与原生接口统一使用该渠道',
  },
  {
    key: 'xunfei',
    text: '讯飞星火认知',
    value: 'xunfei',
    color: 'blue',
    tip: '本渠道基于讯飞 WebSocket 版本 API，如需 HTTP 版本，请使用<strong>讯飞星火认知 V2</strong>渠道',
  },
  {
    key: 'xunfei-v2',
    text: '讯飞星火认知 V2',
    value: 'xunfei-v2',
    color: 'blue',
    tip: 'HTTP 版本的讯飞接口，前往<a href="https://console.xfyun.cn/services/cbm" target="_blank">此处</a>获取 HTTP 服务接口认证密钥',
  },
  {key: 'zhipu', text: '智谱 ChatGLM', value: 'zhipu', color: 'violet'},
  {key: 'ai360', text: '360 智脑', value: 'ai360', color: 'blue'},
  {key: 'moonshot', text: 'Moonshot AI', value: 'moonshot', color: 'black'},
  {key: 'tencent', text: '腾讯混元', value: 'tencent', color: 'teal'},
  {key: 'baichuan', text: '百川大模型', value: 'baichuan', color: 'orange'},
  {key: 'minimax', text: 'MiniMax', value: 'minimax', color: 'red'},
  {key: 'groq', text: 'Groq', value: 'groq', color: 'orange'},
  {key: 'ollama', text: 'Ollama', value: 'ollama', color: 'black'},
  {key: 'lingyiwanwu', text: '零一万物', value: 'lingyiwanwu', color: 'green'},
  {key: 'stepfun', text: '阶跃星辰', value: 'stepfun', color: 'blue'},
  {key: 'coze', text: 'Coze', value: 'coze', color: 'blue'},
  {key: 'cohere', text: 'Cohere', value: 'cohere', color: 'blue'},
  {key: 'deepseek', text: 'DeepSeek', value: 'deepseek', color: 'black'},
  {key: 'cloudflare', text: 'Cloudflare', value: 'cloudflare', color: 'orange'},
  {key: 'deepl', text: 'DeepL', value: 'deepl', color: 'black'},
  {key: 'togetherai', text: 'together.ai', value: 'togetherai', color: 'blue'},
  {key: 'vertexai', text: 'VertexAI', value: 'vertexai', color: 'blue'},
  {key: 'proxy', text: 'Proxy', value: 'proxy', color: 'blue'},
  {key: 'siliconflow', text: 'SiliconFlow', value: 'siliconflow', color: 'blue'},
  {key: 'xai', text: 'xAI', value: 'xai', color: 'blue'},
  {key: 'replicate', text: 'Replicate', value: 'replicate', color: 'blue'},
  {
    key: 'custom',
    text: '自定义渠道',
    value: 'custom',
    color: 'pink',
    tip: '不推荐使用，请使用 <strong>OpenAI</strong>渠道类型。注意，这里所需要填入的代理地址仅会在实际请求时替换域名部分，如果你想填入 OpenAI SDK 中所要求的 Base URL，请使用 OpenAI 渠道类型',
    description: '不推荐使用，请使用 OpenAI 渠道类型',
  },
  {key: 'fastgpt', text: '知识库：FastGPT', value: 'fastgpt', color: 'blue'},
  {key: 'aiproxy-library', text: '知识库：AI Proxy', value: 'aiproxy-library', color: 'purple'},
  {key: 'openrouter', text: 'OpenRouter', value: 'openrouter', color: 'black'},
  {key: 'api2d', text: '代理：API2D', value: 'api2d', color: 'blue'},
  {key: 'openai-sb', text: '代理：OpenAI-SB', value: 'openai-sb', color: 'brown'},
  {key: 'ohmygpt', text: '代理：OhMyGPT', value: 'ohmygpt', color: 'purple'},
  {key: 'aiproxy', text: '代理：AI Proxy', value: 'aiproxy', color: 'purple'},
  {key: 'closeai', text: '代理：CloseAI', value: 'closeai', color: 'teal'},
  {key: 'openai-max', text: '代理：OpenAI Max', value: 'openai-max', color: 'violet'},
  {key: 'ails', text: '代理：AI.LS', value: 'ails', color: 'yellow'},
  {key: 'api2gpt', text: '代理：API2GPT', value: 'api2gpt', color: 'blue'},
  {key: 'aigc2d', text: '代理：AIGC2D', value: 'aigc2d', color: 'purple'},
];
